### ISSUE TITLE
capstone 03 - Take the next step!

### ISSUE THREAD

**Issue by mdewey** [LivCunningham/assignments#33]
# Take the next step!

With the wireframes, HTML and CSS created, next up and will be to continue on breathing life into our projects. After the CSS, HTML, and wireframes, we need to start thinking about breathing life into our apps. Take today to start creating your front end, ERD and API definitions.

## Objectives

- Start making your front end dynamic and creating components
- Create an ERD for your database, at least a first draft
- Start thinking about your API

## Explorer Mode

- A React with your HTML and CSS
- a ERD Diagram on paper/whiteboard/image/online builder
- A read me with your API endpoints Defined

**Comment by LivCunningham** [comment]
https://github.com/LivCunningham/date-genie

Beginning to flesh out the username and login in so that I can see the input change in the console.
Next will be to complete an additional page I realized that I would need to make a new user. This will be a basic form...also need to work on the on change and value input...same as above! 

After that, I need to work on the ERD layout and once again revisiting API's.

**Comment by LivCunningham** [comment]
https://www.figma.com/file/KrQizR9XGeBpXQT7l0DpYq/Date-Genie?node-id=0%3A2
ERD diagram at the bottom below wire frame

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--337d5db9d88e083c06c448999f852548342972b5/giphy-18.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/83)**__
